name: HeiaHeia Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # runs every 5 minutes
  workflow_dispatch:       # allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Download previous seen posts (if any)
        uses: actions/download-artifact@v4
        with:
          name: seen-posts
          path: .
        continue-on-error: true   # <-- allows workflow to keep running if the artifact doesn't exist

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          HEIA_SESSION: ${{ secrets.HEIA_SESSION}}
        run: node bot.js

      - name: Upload updated seen posts
        uses: actions/upload-artifact@v4
        with:
          name: seen-posts
          path: seen_posts.json